version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: dotnet build -c Release

deploy:
  - provider: NuGet
    api_key:
      secure: 7DodQKr3+kFUCGKVwecSGEEuTCkMSQqKQQtQH5zoGPfuFR0Hs53suFu52mulmp8G
    on:
      appveyor_repo_tag: true
